INFO 2023-08-11 20:09:49,021 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:10:38,984 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-11 20:10:41,161 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:20:04,270 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-11 20:20:04,564 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:20:18,990 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:24:36,685 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:26:37,610 autoreload:668 Watching for file changes with StatReloader
WARNING 2023-08-11 20:31:12,552 log:241 Not Found: /host/
WARNING 2023-08-11 20:31:12,552 basehttp:212 "GET /host/ HTTP/1.1" 404 2356
ERROR 2023-08-11 20:32:07,591 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:07,624 log:241 Bad Request: /
WARNING 2023-08-11 20:32:07,625 basehttp:212 "GET / HTTP/1.1" 400 76742
ERROR 2023-08-11 20:32:08,556 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:08,574 log:241 Bad Request: /favicon.ico
WARNING 2023-08-11 20:32:08,575 basehttp:212 "GET /favicon.ico HTTP/1.1" 400 76667
ERROR 2023-08-11 20:32:14,783 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:14,799 log:241 Bad Request: /host
WARNING 2023-08-11 20:32:14,800 basehttp:212 "GET /host HTTP/1.1" 400 76786
ERROR 2023-08-11 20:32:14,877 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:14,894 log:241 Bad Request: /favicon.ico
WARNING 2023-08-11 20:32:14,895 basehttp:212 "GET /favicon.ico HTTP/1.1" 400 76671
ERROR 2023-08-11 20:32:46,519 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:46,544 log:241 Bad Request: /host/get
WARNING 2023-08-11 20:32:46,545 basehttp:212 "GET /host/get HTTP/1.1" 400 76830
ERROR 2023-08-11 20:32:46,626 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:46,643 log:241 Bad Request: /favicon.ico
WARNING 2023-08-11 20:32:46,644 basehttp:212 "GET /favicon.ico HTTP/1.1" 400 76675
ERROR 2023-08-11 20:32:57,415 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:57,428 log:241 Bad Request: /host/get
WARNING 2023-08-11 20:32:57,429 basehttp:212 "GET /host/get HTTP/1.1" 400 76967
ERROR 2023-08-11 20:32:57,516 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:57,529 log:241 Bad Request: /favicon.ico
WARNING 2023-08-11 20:32:57,530 basehttp:212 "GET /favicon.ico HTTP/1.1" 400 76675
INFO 2023-08-11 20:32:57,843 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\urls.py changed, reloading.
INFO 2023-08-11 20:32:58,156 autoreload:668 Watching for file changes with StatReloader
ERROR 2023-08-11 20:32:58,526 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:58,544 log:241 Bad Request: /host/get
WARNING 2023-08-11 20:32:58,544 basehttp:212 "GET /host/get HTTP/1.1" 400 76967
ERROR 2023-08-11 20:32:58,613 exception:124 Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\http\request.py", line 150, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '127.0.0.1:8888'. You may need to add '127.0.0.1' to ALLOWED_HOSTS.
WARNING 2023-08-11 20:32:58,631 log:241 Bad Request: /favicon.ico
WARNING 2023-08-11 20:32:58,632 basehttp:212 "GET /favicon.ico HTTP/1.1" 400 76675
INFO 2023-08-11 20:33:25,259 autoreload:668 Watching for file changes with StatReloader
WARNING 2023-08-11 20:33:29,420 log:241 Not Found: /
WARNING 2023-08-11 20:33:29,420 basehttp:212 "GET / HTTP/1.1" 404 2274
WARNING 2023-08-11 20:33:30,094 log:241 Not Found: /favicon.ico
WARNING 2023-08-11 20:33:30,095 basehttp:212 "GET /favicon.ico HTTP/1.1" 404 2325
WARNING 2023-08-11 20:33:34,999 log:241 Not Found: /host
WARNING 2023-08-11 20:33:35,000 basehttp:212 "GET /host HTTP/1.1" 404 2304
WARNING 2023-08-11 20:33:39,573 log:241 Not Found: /host/
WARNING 2023-08-11 20:33:39,574 basehttp:212 "GET /host/ HTTP/1.1" 404 2359
WARNING 2023-08-11 20:33:44,168 log:241 Not Found: /host/get
WARNING 2023-08-11 20:33:44,169 basehttp:212 "GET /host/get HTTP/1.1" 404 2368
INFO 2023-08-11 20:33:53,858 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\urls.py changed, reloading.
INFO 2023-08-11 20:33:54,167 autoreload:668 Watching for file changes with StatReloader
WARNING 2023-08-11 20:33:57,882 log:241 Not Found: /host/
WARNING 2023-08-11 20:33:57,882 basehttp:212 "GET /host/ HTTP/1.1" 404 2356
WARNING 2023-08-11 20:34:03,552 log:241 Not Found: /host
WARNING 2023-08-11 20:34:03,553 basehttp:212 "GET /host HTTP/1.1" 404 2304
WARNING 2023-08-11 20:34:29,447 log:241 Not Found: /host/
WARNING 2023-08-11 20:34:29,447 basehttp:212 "GET /host/ HTTP/1.1" 404 2356
INFO 2023-08-11 20:34:37,340 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\urls.py changed, reloading.
INFO 2023-08-11 20:34:37,658 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:34:40,373 basehttp:212 "GET /host/ HTTP/1.1" 200 5137
INFO 2023-08-11 20:34:40,553 basehttp:212 "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
INFO 2023-08-11 20:34:40,553 basehttp:212 "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
INFO 2023-08-11 20:34:40,553 basehttp:212 "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
INFO 2023-08-11 20:34:40,556 basehttp:212 "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
INFO 2023-08-11 20:34:40,557 basehttp:212 "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
INFO 2023-08-11 20:34:40,558 basehttp:212 "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
INFO 2023-08-11 20:34:40,558 basehttp:212 "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
INFO 2023-08-11 20:34:40,559 basehttp:212 "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
INFO 2023-08-11 20:34:40,559 basehttp:212 "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
INFO 2023-08-11 20:34:40,560 basehttp:212 "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
INFO 2023-08-11 20:34:40,567 basehttp:212 "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
INFO 2023-08-11 20:44:47,314 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-11 20:44:47,632 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:50:24,396 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:51:24,995 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\users\urls.py changed, reloading.
INFO 2023-08-11 20:51:27,965 autoreload:668 Watching for file changes with StatReloader
INFO 2023-08-11 20:51:33,214 basehttp:212 "GET /host/ HTTP/1.1" 200 5137
INFO 2023-08-11 20:51:44,222 basehttp:212 "GET /users/login HTTP/1.1" 301 0
ERROR 2023-08-11 20:51:44,265 log:241 Internal Server Error: /users/login/
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: 方法 “GET” 不被允许。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\module_loading.py", line 15, in cached_import
    module = import_module(module_path)
  File "D:\softs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'uric_api'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'uric_api.utils.exceptions.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ModuleNotFoundError: No module named 'uric_api'.
ERROR 2023-08-11 20:51:44,269 basehttp:212 "GET /users/login/ HTTP/1.1" 500 144239
INFO 2023-08-11 20:53:00,269 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\settings\dev.py changed, reloading.
INFO 2023-08-11 20:53:00,564 autoreload:668 Watching for file changes with StatReloader
WARNING 2023-08-11 20:53:03,897 log:241 Method Not Allowed: /users/login/
WARNING 2023-08-11 20:53:03,898 basehttp:212 "GET /users/login/ HTTP/1.1" 405 7647
ERROR 2023-08-11 20:53:28,411 log:241 Internal Server Error: /users/login
Traceback (most recent call last):
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\utils\deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
  File "R:\zcx\PyCode\AutoOps\venv\lib\site-packages\django\middleware\common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to api.zcx321.cc:8888/users/login/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
ERROR 2023-08-11 20:53:28,412 basehttp:212 "POST /users/login HTTP/1.1" 500 75567
INFO 2023-08-11 20:55:13,085 basehttp:212 "POST /users/login/ HTTP/1.1" 200 483
INFO 2023-08-11 21:12:08,667 autoreload:266 R:\zcx\PyCode\AutoOps\backend\backend\apps\host\models.py changed, reloading.
